edition = "2024"
max_width = 100
comment_width = 100
wrap_comments = true
format_code_in_doc_comments = true
normalize_doc_attributes = true

reorder_imports = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_impl_items = true

use_field_init_shorthand = true
newline_style = "Unix"
